title: Mateusz Szymczyk
tagline: Site Reliability Engineering Consultant
description: Tailored Reliability - making systems reliable by design, not by accident.
email: ds4tch@gmail.com

github_username:  ds4tch
repository: ds4tech/ds4tech.github.io

# Build settings
# theme: minima
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-feed
- jekyll-remote-theme
# - jekyll-sitemap



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
